### ISSUE TITLE
Set number of threads

### ISSUE THREAD

**Issue by lyifa** [Enchufa2/r-flexiblas#1]
I use R on Fedora 33. Based on your R blogger post, R should be using the OpenMP version of OpenBLAS on my computer. Do I still need to set the number of threads to get better performance using your flexiblas R package? Or the the OpenMP version of OpenBLAS already uses multiple threads?

**Comment by Enchufa2** [comment]
You are using multiple threads by default. In my system, I see:

```r
> parallel::detectCores()
[1] 8
> flexiblas::flexiblas_get_num_threads()
[1] 8
```
