### ISSUE TITLE
BLAS/LAPACK routine 'DLASCL' gave error code -4

### ISSUE THREAD

**Issue by davedgd** [Enchufa2/r-flexiblas#2]
Thanks for putting this package together -- it's nice to have easy control over BLAS in Fedora!

I've run into an issue with it however. While I was able to replicate the R-bloggers [example](https://www.r-bloggers.com/2020/10/installing-and-switching-to-mkl-on-fedora/), I ran into an issue running the sample code from this StackOverflow [post](https://stackoverflow.com/questions/38090206/linking-intels-math-kernel-library-mkl-to-r-on-windows).

Specifically, running this code produces an error (`m` is set to `1000` here instead of `10000` as in the StackOverflow original since it errors quickly):

```R
# Singular Value Decomposition
m <- 1000
n <- 2000
A <- matrix (runif (m*n),m,n)
system.time (S <- svd (A,nu=0,nv=0))
```

Within RStudio, I received:

`BLAS/LAPACK routine 'DLASCL' gave error code -4`

Similarly, I ran into issues running this from the terminal. I tried this with intel-mkl-2020.0-088, the 2019.5 version, as well as the most recent oneAPI (although admittedly for the latter I didn't test it fully).

The expected result should be a relatively quick calculation -- at least it is on macOS and Windows.

**Comment by Enchufa2** [comment]
Could you paste the output from `sessionInfo()`, please? Also, does it fail with a specific backend? Did you use the CRAN package or did you install flexiblas from the system repositories? I have `R-flexiblas` installed from the system repositories in Fedora 33 and I cannot reproduce the error (with `10000`).

**Comment by davedgd** [comment]
@Enchufa2: thanks for the quick reply!

To clarify, I used the system repositories and tried OpenBLAS and MKL (intel-mkl-2020.0-088) following your R-bloggers guides, which worked perfectly for the benchmark example in the post. The code in the issue works with the default Fedora 33 OpenBLAS backend but fails when switching the backend to MKL. All of this was done with a fresh, fully-updated Fedora install. 

I will post my sessionInfo() next time I’m at the computer along with some screenshots. Hopefully I can help replicate this.

**Comment by davedgd** [comment]
Here is the sessionInfo:

```R
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 33 (Cinnamon)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libflexiblas.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] flexiblas_3.0.0

loaded via a namespace (and not attached):
[1] compiler_4.0.4 tools_4.0.4   
```

I've also attached screenshots showing 1) everything working fine with OpenBLAS; 2) the MKL error; and 3) sessionInfo:

**Fine with OpenBLAS**
![OpenBLAS](https://user-images.githubusercontent.com/4490587/111647463-e5061980-87d8-11eb-848c-19db001a005a.png)

**Error with MKL**
![MKL](https://user-images.githubusercontent.com/4490587/111647498-eafbfa80-87d8-11eb-8414-35e8115e961c.png)

**sessionInfo**
![sessionInfo](https://user-images.githubusercontent.com/4490587/111647487-e9323700-87d8-11eb-8c90-be50b6e0cdbd.png)

**Comment by davedgd** [comment]
Sorry, one more screenshot showing how everything is oddly fine with the R-bloggers code:

![RBloggers](https://user-images.githubusercontent.com/4490587/111648698-03b8e000-87da-11eb-8a98-436ff00990e8.png)

**Comment by Enchufa2** [comment]
Thanks for all the details. Strange, indeed. Let's summon @grisuthedragon here, maybe this rings a bell to him.

**Comment by grisuthedragon** [comment]
Never use the MKL_RT interface. That is more (or less) dangerous. The problem is that the `mkl_rt.so` contains an interface with a flexible ABI controlled by some environment variables and in this way its interface is not reblas compatible. This causes most of the errors I think.  For example one can change the width of an integer and the threading model via environment variables and API calls.

The solution would be to create custumized MKL interfaces using the **mklbuilder** Makefile.  Can you try this? 
Details are there: https://github.com/mpimd-csc/flexiblas/issues/13

The .so file created with this tool is refblas compatible and thus can be loaded as you did it. 

@Enchufa2  yes it ringed a bell ;-)

**Comment by davedgd** [comment]
@grisuthedragon: Yes, perfect! This solution works. I used the following code from your example, but modified for a parallel version:

```
make libintel64 export=blas_example_list interface=lp64 parallel=gnu threading=parallel name=flexiblas_mkl_parallel
```

I am now seeing performance approaching what I should get for MKL (using the `MKL_DEBUG_CPU_TYPE=5` workaround for Ryzen):

```R
> flexiblas_list_loaded()
[1] "OPENBLAS-OPENMP"                                
[2] "/home/daved/Downloads/flexiblas_mkl_parallel.so"
> 
> flexiblas_switch(2)
> flexiblas_current_backend()
[1] "/home/daved/Downloads/flexiblas_mkl_parallel.so"
> 
> flexiblas_set_num_threads(16)
> 
> m <- 10000
> n <- 2000
> A <- matrix (runif (m*n),m,n)
> system.time (S <- svd (A,nu=0,nv=0))
   user  system elapsed 
 15.487   0.181   2.294 
> 
> flexiblas_get_num_threads()
[1] 1
```

Which compares favorably with OpenBLAS when set equal to the number of physical cores (e.g., 16 for my 3950X):

```R
> flexiblas_list_loaded()
[1] "OPENBLAS-OPENMP"                                
[2] "/home/daved/Downloads/flexiblas_mkl_parallel.so"
> 
> flexiblas_switch(1)
> flexiblas_current_backend()
[1] "OPENBLAS-OPENMP"
> 
> flexiblas_set_num_threads(16)
> 
> m <- 10000
> n <- 2000
> A <- matrix (runif (m*n),m,n)
> system.time (S <- svd (A,nu=0,nv=0))
   user  system elapsed 
 28.464   3.108   2.869 
> 
> flexiblas_get_num_threads()
[1] 16
```

The only lingering (and separate) issue here is that **flexiblas_get_num_threads** does not seem to work when using this customized MKL interface, but this can be solved via export commands.

Thank you!

**Comment by Enchufa2** [comment]
Nice! I should update the post then with these instructions... My bad. :)

**Comment by davedgd** [comment]
No worries! =) I never would have found this easy MKL solution if not for your post (first result in Google atm). Thanks again to both of you!

**Comment by Enchufa2** [comment]
Let me keep this open to remind me to update the post. ;-)

**Comment by grisuthedragon** [comment]
In the next release (whenever I developed enough new stuff), we include a more extended verision of the text in mpimd-csc/flexiblas#13 including the way to add the MKL.
